import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const index = readFileSync(new URL("../public/index.html", import.meta.url), "utf8");
const styles = readFileSync(new URL("../public/styles.css", import.meta.url), "utf8");
const client = readFileSync(new URL("../public/app.js", import.meta.url), "utf8");
const i18n = readFileSync(new URL("../public/i18n.js", import.meta.url), "utf8");
const authRoutes = readFileSync(new URL("../src/routes/auth.routes.ts", import.meta.url), "utf8");
const dataRoutes = readFileSync(new URL("../src/routes/data.routes.ts", import.meta.url), "utf8");
const migration = readFileSync(new URL("../migrations/008_user_account_settings.sql", import.meta.url), "utf8");
const loginHistoryMigration = readFileSync(new URL("../migrations/025_login_history.sql", import.meta.url), "utf8");
const loginHistoryOutcomeMigration = readFileSync(new URL("../migrations/033_login_history_locked_outcome.sql", import.meta.url), "utf8");
const loginHistoryCountryMigration = readFileSync(new URL("../migrations/044_login_history_country.sql", import.meta.url), "utf8");
const authSessionMigration = readFileSync(new URL("../migrations/052_auth_device_sessions.sql", import.meta.url), "utf8");
const countryLoginPolicyMigration = readFileSync(new URL("../migrations/045_country_login_access_policy.sql", import.meta.url), "utf8");
const themeMigration = readFileSync(new URL("../migrations/034_user_theme_preference.sql", import.meta.url), "utf8");
const themeBootstrap = readFileSync(new URL("../public/theme-bootstrap.js", import.meta.url), "utf8");

describe("Account settings layer", () => {
  it("opens from the sidebar identity card and groups profile, language, security, and logout", () => {
    expect(index).toContain('id="account-settings-trigger"');
    expect(index).toContain('role="dialog"');
    expect(index).toContain('aria-modal="true"');
    expect(index).toContain('data-account-panel="profile"');
    expect(index).toContain('data-account-panel="preferences"');
    expect(index).toContain('data-account-panel="security"');
    expect(index).toContain('data-account-panel="data"');
    expect(index).toContain('id="account-avatar-input"');
    expect(index).toContain('id="language-select"');
    expect(index).toContain('id="theme-select"');
    expect(index).toContain('value="light"');
    expect(index).toContain('value="dark"');
    expect(index).toContain('id="account-current-password"');
    expect(index).toContain('data-security-panel="sessions"');
    expect(index).toContain('id="account-active-sessions-body"');
    expect(index).toContain('data-i18n="account.activeSessionsIp"');
    expect(index).toContain('data-security-panel="history"');
    expect(index).toContain('data-security-panel="blocks"');
    expect(index).toContain('id="account-login-history-months"');
    expect(index).toContain('id="account-login-history-body"');
    expect(index).toContain('id="account-block-history-body"');
    expect(index).toContain('id="account-country-login-mode"');
    expect(index).toContain('value="ALLOWLIST"');
    expect(index).toContain('value="BLOCKLIST"');
    expect(index).toContain('data-i18n="account.loginHistoryCountry"');
    expect(index).toContain('id="account-data-export"');
    expect(index).toContain('id="account-data-input"');
    expect(index).toContain('id="account-data-import"');
    expect(index).toContain('id="logout-button"');
    expect(index).not.toContain('class="language-switcher"');
  });

  it("manages focus, keyboard dismissal, avatar resizing, and account API calls", () => {
    expect(client).toContain("function openAccountSettings");
    expect(client).toContain("function closeAccountSettings");
    expect(client).toContain('event.key === "Escape"');
    expect(client).toContain("getAccountSettingsFocusableElements");
    expect(client).toContain('canvas.toDataURL("image/webp", 0.86)');
    expect(client).toContain('api("/api/auth/profile"');
    expect(client).toContain('api("/api/auth/password"');
    expect(client).toContain('api("/api/auth/sessions")');
    expect(client).toContain('async function revokeActiveSession');
    expect(client).toContain('/api/auth/login-history?months=');
    expect(client).toContain("function renderLoginHistory");
    expect(client).toContain("function renderBlockHistory");
    expect(client).toContain("async function saveCountryLoginPolicy");
    expect(client).toContain("function formatLoginCountry");
    expect(client).toContain("applyUserPreferredLanguage");
    expect(client).toContain("applyUserTheme");
    expect(client).toContain('enqueueAccountProfilePatch(targetKey, { theme: nextTheme })');
    expect(client).toContain('fetch("/api/data/export"');
    expect(client).toContain('api("/api/data/import"');
  });

  it("includes responsive modal styling, localized copy, and persistent schema support", () => {
    expect(styles).toContain(".account-settings-layer");
    expect(styles).toContain(".account-settings-dialog");
    expect(styles).toContain("body.account-settings-open");
    expect(styles).toMatch(/\.account-settings-backdrop:hover,[\s\S]*background:\s*rgba\(29, 45, 57, 0\.36\);/);
    expect(styles).toContain("@media (max-width: 760px)");
    expect(styles).toContain(".login-history-table");
    expect(styles).toContain(".login-history-result.failure");
    expect(styles).toContain('html[data-theme="dark"]');
    expect(styles).toContain('--chrome-canvas: #17191d');
    expect(styles).toContain('.rendered-kanban-card--pink');
    expect(styles).toContain('.rendered-database-card');
    expect(styles).toContain('.rendered-gantt-stage');
    expect(styles).toMatch(/\.account-settings-dialog\s*\{[^}]*border-radius:\s*var\(--radius-lg\);/s);
    expect(styles).toMatch(/\.account-preference-card\s*\{[^}]*border-radius:\s*8px;/s);
    expect(styles).toContain("border-radius: var(--radius-lg) var(--radius-lg) 0 0;");
    expect(i18n).toContain('open: "계정 설정 열기"');
    expect(i18n).toContain('passwordChanged: "비밀번호를 변경했습니다."');
    expect(i18n).toContain('activeSessionsTab: "로그인된 기기"');
    expect(i18n).toContain('activeSessionsIp: "IP 주소"');
    expect(i18n).toContain('loginHistoryTitle: "로그인 기록"');
    expect(i18n).toContain('loginHistorySummary: "최근 {months}개월 · 총 {count}건"');
    expect(i18n).toContain('loginHistoryCountry: "국가"');
    expect(i18n).toContain('blockHistoryTab: "차단 기록"');
    expect(i18n).toContain('countryLoginTitle: "IP 국가별 로그인 제한"');
    expect(i18n).toContain('exportTitle: "모든 데이터 내보내기"');
    expect(i18n).toContain('importTitle: "백업 복원"');
    expect(i18n).toContain('themeLight: "일반 테마"');
    expect(i18n).toContain('themeDark: "다크 테마"');
    expect(authRoutes).toContain('authRouter.patch("/profile"');
    expect(authRoutes).toContain('authRouter.post("/password"');
    expect(authRoutes).toContain('authRouter.get("/sessions", requireAuth');
    expect(authRoutes).toContain('authRouter.delete("/sessions/:sessionId", requireAuth');
    expect(authRoutes).toContain('"/login-history"');
    expect(authRoutes).toContain('"/block-history"');
    expect(authRoutes).toContain('"/country-login-policy"');
    expect(authRoutes).toContain('decision === "LOCKED" ? "LOCKED" : "FAILURE"');
    expect(client).toContain('attempt.outcome === "LOCKED"');
    expect(i18n).toContain('loginHistoryLocked: "Locked"');
    expect(authRoutes).toContain("verifyPassword(currentPassword");
    expect(dataRoutes).toContain('dataRouter.get("/export", dataExportRateLimit');
    expect(dataRoutes).toContain('dataRouter.post("/import"');
    expect(migration).toContain("avatar_data MEDIUMTEXT");
    expect(migration).toContain("preferred_language VARCHAR(10)");
    expect(loginHistoryMigration).toContain("CREATE TABLE IF NOT EXISTS user_login_attempts");
    expect(loginHistoryMigration).toContain("outcome ENUM('SUCCESS', 'FAILURE')");
    expect(loginHistoryOutcomeMigration).toContain("ENUM('SUCCESS', 'FAILURE', 'LOCKED')");
    expect(loginHistoryCountryMigration).toContain("country_code CHAR(2)");
    expect(loginHistoryCountryMigration).toContain("country_dataset_updated_at DATETIME(3)");
    expect(authSessionMigration).toContain("CREATE TABLE IF NOT EXISTS user_auth_sessions");
    expect(authSessionMigration).toContain("browser_name VARCHAR(64)");
    expect(authSessionMigration).toContain("ip_address VARCHAR(45)");
    expect(countryLoginPolicyMigration).toContain("country_login_mode ENUM('OFF', 'ALLOWLIST', 'BLOCKLIST')");
    expect(countryLoginPolicyMigration).toContain("CREATE TABLE IF NOT EXISTS user_country_login_blocks");
    expect(themeMigration).toContain("ENUM('light', 'dark')");
    expect(themeBootstrap).toContain('localStorage.getItem(storageKey)');
    expect(themeBootstrap).toContain('document.documentElement.dataset.theme = theme');
    expect(loginHistoryMigration).toContain("source_ip VARCHAR(45)");
  });
});
