ALTER TABLE blocks
  MODIFY COLUMN type ENUM('MARKDOWN', 'HEADING_1', 'HEADING_2', 'HEADING_3', 'TODO', 'QUOTE', 'CALLOUT', 'TABLE', 'KANBAN', 'DATABASE', 'BOOKMARK', 'CODE', 'DIVIDER', 'IMAGE', 'ATTACHMENT')
  NOT NULL DEFAULT 'MARKDOWN';
