ALTER TABLE pages
  ADD COLUMN IF NOT EXISTS edit_version BIGINT UNSIGNED NOT NULL DEFAULT 1 AFTER parent_page_id;

ALTER TABLE blocks
  ADD COLUMN IF NOT EXISTS edit_version BIGINT UNSIGNED NOT NULL DEFAULT 1 AFTER metadata;
