ALTER TABLE pages
  MODIFY COLUMN cover_url MEDIUMTEXT NULL,
  ADD COLUMN IF NOT EXISTS cover_position_x TINYINT UNSIGNED NOT NULL DEFAULT 50 AFTER cover_url,
  ADD COLUMN IF NOT EXISTS cover_position_y TINYINT UNSIGNED NOT NULL DEFAULT 50 AFTER cover_position_x;
